---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for Prowler

Parameters:

  ProwlerAccount:
    Description: AWS account ID where Prowler is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  ProwlerRoleExternalId:
    Description: Prowler Role ExternalID
    Type: String

Resources:

  ProwlerOrganizationsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prowler-organizations-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${ProwlerAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${ProwlerRoleExternalId}'
      Policies:
      - PolicyName: "AllowOrganizationListAccounts"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: organizations:ListAccounts
            Resource: '*'
