---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for Prowler

Parameters:

  ProwlerAccount:
    Description: AWS account ID where Prowler is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID

  ProwlerRoleExternalId:
    Description: Prowler Role ExternalID
    Type: String

  ProwlerStackSetSpokeName:
    Description: Name of the StackSet in charge of distributing spoke account assets
    Type: String
    Default: prowler-spoke-account

Resources:

  ProwlerOrganizationsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prowler-organizations-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${ProwlerAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${ProwlerRoleExternalId}'
      Policies:
      - PolicyName: "AllowOrganizationListAccounts"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: organizations:ListAccounts
            Resource: '*'
      - PolicyName: "AllowUpdateStackInstances"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action: cloudformation:CreateStackInstances
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stackset/${ProwlerStackSetSpokeName}:*"
