AWSTemplateFormatVersion: '2010-09-09'
Description: Common resources for Prowler Batch
# Stack Name : prowler-common
# Description : this stack creates the Prowler main stack prerequisites :
# - one ECR repository
# - if needed, one S3 bucket to store reports (otherwise use an external one)

Parameters:

  TagBlock:
    Description: Applicative block tag
    Type: String
    Default: security

  TagApp:
    Description: Application tag
    Type: String
    Default: prowler

  TagOrg:
    Description: Organization tag
    Type: String
    Default: cloudteam

  ProwlerEcrRepoName:
    Description: ECR name for the Prowler repo
    Type: String
    Default: prowler

  UseOwnReportingBucket:
    Description: Enable a dedicated Bucket to store reports
    Type: String
    Default: true
    AllowedValues: [true, false]

Conditions:
  HasProwlerOwnReportingBucket: !Equals [!Ref UseOwnReportingBucket, true]

Resources:

  ProwlerEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProwlerEcrRepoName}'

  ProwlerReportingBucket:
    Type: AWS::S3::Bucket
    Condition: HasProwlerOwnReportingBucket
    Properties:
      BucketName: !Sub '${TagApp}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: Block
        Value: !Sub '${TagBlock}'
      - Key: App
        Value: !Sub '${TagApp}'
      - Key: Org
        Value: !Sub '${TagOrg}'

Outputs:

  ProwlerEcrRepository:
    Description: Prowler ECR repository
    Value: !GetAtt ProwlerEcrRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepository"
